# Generated by Django 3.1.8 on 2023-02-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230216_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_inappropriate',
            field=models.BooleanField(default=False),
        ),
    ]
